### ISSUE TITLE
Invite user to more than 2 roles?

### ISSUE THREAD

**Issue by SuecoMarcus** [ARISEChurch/discord-invite-roles#1]
Hi!

I'm trying to add a user to **3 roles**, but only 2 roles are assigned.

Am I doing something wrong?

**Comment by tim-smart** [comment]
I just checked the logs to see if there were any errors, and could see this:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/40680/212572446-6bfab4f3-9b5b-408a-bd32-d4b7b375c0b7.png">

So it seems like it should be working.

**Comment by SuecoMarcus** [comment]
Interesting, but for some reason, it's not working properly:

<img width="381" alt="Screen Shot 2023-01-15 at 20 46 41" src="https://user-images.githubusercontent.com/6123682/212574119-1a237965-4318-4155-8a8d-976fcee61bf4.png">

**Comment by SuecoMarcus** [comment]
And this is what I see in our logs:

<img width="421" alt="Screen Shot 2023-01-15 at 20 49 12" src="https://user-images.githubusercontent.com/6123682/212574203-590db880-d683-476f-b63a-19697fbe244a.png">

**Comment by SuecoMarcus** [comment]
And this is how the channel topic is configured:

`[[students, bootcamp, bootcamp-g2301]]`

**Comment by tim-smart** [comment]
I have made a tweak to the role adding code, try again and see how you go.

**Comment by SuecoMarcus** [comment]
Excellent! Thank you very much!
